/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SystemImport } from './routes/system'
import { Route as SettingsImport } from './routes/settings'
import { Route as ScheduledImport } from './routes/scheduled'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as ModelsImport } from './routes/models'
import { Route as McpImport } from './routes/mcp'
import { Route as ConnectImport } from './routes/connect'
import { Route as IndexImport } from './routes/index'
import { Route as CChatIdImport } from './routes/c.$chatId'

// Create/Update Routes

const SystemRoute = SystemImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ScheduledRoute = ScheduledImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const ModelsRoute = ModelsImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRoute,
} as any)

const McpRoute = McpImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRoute,
} as any)

const ConnectRoute = ConnectImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CChatIdRoute = CChatIdImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectImport
      parentRoute: typeof rootRoute
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpImport
      parentRoute: typeof rootRoute
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemImport
      parentRoute: typeof rootRoute
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/mcp'
    | '/models'
    | '/onboarding'
    | '/scheduled'
    | '/settings'
    | '/system'
    | '/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/mcp'
    | '/models'
    | '/onboarding'
    | '/scheduled'
    | '/settings'
    | '/system'
    | '/c/$chatId'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/mcp'
    | '/models'
    | '/onboarding'
    | '/scheduled'
    | '/settings'
    | '/system'
    | '/c/$chatId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  McpRoute: typeof McpRoute
  ModelsRoute: typeof ModelsRoute
  OnboardingRoute: typeof OnboardingRoute
  ScheduledRoute: typeof ScheduledRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  CChatIdRoute: typeof CChatIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  McpRoute: McpRoute,
  ModelsRoute: ModelsRoute,
  OnboardingRoute: OnboardingRoute,
  ScheduledRoute: ScheduledRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  CChatIdRoute: CChatIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/connect",
        "/mcp",
        "/models",
        "/onboarding",
        "/scheduled",
        "/settings",
        "/system",
        "/c/$chatId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/connect": {
      "filePath": "connect.tsx"
    },
    "/mcp": {
      "filePath": "mcp.tsx"
    },
    "/models": {
      "filePath": "models.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/scheduled": {
      "filePath": "scheduled.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/system": {
      "filePath": "system.tsx"
    },
    "/c/$chatId": {
      "filePath": "c.$chatId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
